services:
  # PHP
  php:
    container_name: ${APP_NAME}.php
    build:
      context: ./
      dockerfile: docker/php/php.dockerfile
      args:
        - WORKDIR=${WORKDIR}
    restart: on-failure
    working_dir: ${WORKDIR}
    volumes:
      - ./src/:${WORKDIR}
    networks:
      - enetwork

  # NGINX
  nginx:
    container_name: ${APP_NAME}.nginx
    image: nginx:alpine
    restart: on-failure
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./docker/nginx/default.conf/:/etc/nginx/conf.d/default.conf
      - ./src/:${WORKDIR}
    networks:
      - enetwork
    depends_on:
      - php

networks:
  enetwork:
    external: true
